---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: remove-resources-from-pods
  labels:
    app: remove-resources-from-pods
webhooks:
  - name: remove-resources-from-pods.pod-res-wh.svc.cluster.local
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      caBundle: changeme
      service:
        name: remove-resources-from-pods
        namespace: pod-res-wh
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - {key: removepodresources, operator: In, values: ["yes"]}

